<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-U258E43" name="com.taller3.sistemamio.unit_tests.ServiciosServicioTest" tests="5" failures="0" timestamp="23 Sep 2019 23:45:06 GMT" time="1.571" errors="1">
  <testcase name="testAddServiceNullConductor" time="0.011" classname="com.taller3.sistemamio.unit_tests.ServiciosServicioTest"/>
  <testcase name="testAddServiceNull" time="0.023" classname="com.taller3.sistemamio.unit_tests.ServiciosServicioTest"/>
  <testcase name="testAddServiceNullBus" time="0.008" classname="com.taller3.sistemamio.unit_tests.ServiciosServicioTest"/>
  <testcase name="testAddServiceCorect" time="1.524" classname="com.taller3.sistemamio.unit_tests.ServiciosServicioTest"/>
  <testcase name="testAddServiceNullRuta" time="0.005" classname="com.taller3.sistemamio.unit_tests.ServiciosServicioTest">
    <error type="org.testng.TestException" message="
The exception was thrown with the wrong message: expected &quot;La ruta debe estar registrada&quot; but got &quot;La ruta debe de estar registrado&quot;">
      <![CDATA[org.testng.TestException: 
The exception was thrown with the wrong message: expected "La ruta debe estar registrada" but got "La ruta debe de estar registrado"
at org.testng.internal.ExpectedExceptionsHolder.wrongException(ExpectedExceptionsHolder.java:71)
at org.testng.internal.Invoker.considerExceptions(Invoker.java:1130)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.Exception: La ruta debe de estar registrado
at co.edu.icesi.miniproyecto.services.ServiciosServicioImpl.addServicio(ServiciosServicioImpl.java:35)
at com.taller3.sistemamio.unit_tests.ServiciosServicioTest.testAddServiceNullRuta(ServiciosServicioTest.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
... 19 more
]]>
    </error>
  </testcase> <!-- testAddServiceNullRuta -->
</testsuite> <!-- com.taller3.sistemamio.unit_tests.ServiciosServicioTest -->
